### ISSUE TITLE
Installation through rubygems

### ISSUE THREAD

**Issue by knightq** [barsoom/prawn-print#5]
## The issue

In the `README.markdown` the installation steps suggest to install this gem with git.
On rubygem there are the equivalent gems published.
Why shall we install this gem from git?

## Proposal

If they are the same (I think so), it would be better to change the documentation from
`gem 'prawn-print', :git => 'git://github.com/barsoom/prawn-print.git'`

to

`gem 'prawn-print'`

**Comment by henrik** [comment]
:thumbsup: Sounds good. Wanna make a Pull Request?

**Comment by knightq** [comment]
Sure, here it is: https://github.com/barsoom/prawn-print/pull/6

**Comment by henrik** [comment]
Merged, with thanks!
