### ISSUE TITLE
redirect back option after print

### ISSUE THREAD

**Issue by MitsunChieh** [barsoom/prawn-print#7]
prawn will open the pdf in current window with option { disposition: 'inline' }
I'd like to let it redirect to previous page after window.print() is done

**Comment by henrik** [comment]
Hi,

I haven't touched this lib in years, and I'm not sure about any of this, so take it with a grain of salt:

As I remember it, JavaScript support in PDFs is/was for Adobe Reader only. And I think perhaps Adobe Reader doesn't open within the current browser window – if that happens, it's probably your browser's built-in PDF rendering, which might not support JavaScript.

So perhaps this isn't achievable. Does the auto-printing work work it opens in the current window? I.e. does a print dialog automatically appear, or does it even start printing without a dialog?

You could *try* something like `add_docopen_js("window.history.back();")` in your document after adding this library, but I doubt it will work.

You could also try something completely different like [Google Cloud Print](https://www.google.com/cloudprint/learn/).
